apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fault-injector
  namespace: __APP_NAMESPACE__
  labels:
    app: kube-prometheus-stack
    release: __HELM_RELEASE__
spec:
  selector:
    matchLabels:
      app: fault-injector
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
