apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-healthy
  labels:
    scenario: healthy
spec:
  capacity:
    storage: 100Mi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/local-pvc/vol1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [pvc-monitoring-poc-control-plane]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-filling
  labels:
    scenario: filling
spec:
  capacity:
    storage: 10Mi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/local-pvc/vol2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [pvc-monitoring-poc-control-plane]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-fault
  labels:
    scenario: fault-injection
spec:
  capacity:
    storage: 100Mi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/local-pvc/vol3
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [pvc-monitoring-poc-control-plane]
